column_comments = {
    "salesforce_account": {
        "id": "The Salesforce account ID",
        "name": "account name",
        "createddate": "The Salesforce account creation date",
        "lastmodifieddate": "The Salesforce account last modified date",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    },
    "salesforce_accounthistory": {
        "field": "The Salesforce account field type",
        "oldvalue": "account old value",
        "newvalue": "account new value",
        "accountid": "account ID",
        "createddate": "The Salesforce account creation date",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    },
    "salesforce_cases": {
        "id": "Unique identifier for the case",
        "type": "Type of case (e.g., complaint, inquiry)",
        "status": "Current status of the case (e.g., Open, Closed, Pending)",
        "customer_reference_id__c": "Reference ID provided by the customer",
        "priority": "Priority level of the case (e.g., High, Medium, Low)",
        "description": "Detailed description of the case",
        "createddate": "Date and time when the case was created",
        "lastmodifieddate": "Date and time when the case was last updated",
        "closeddate": "Date and time when the case was closed",
        "ownerid": "Unique identifier of the case owner (assigned agent)",
        "origin": "Source of the case (e.g., Email, Phone, Web)",
        "contactid": "Unique identifier of the associated contact",
        "casenumber": "System-generated case number",
        "case_record_type_name__c": "Name of the case record type",
        "case_rt_dev_name__c": "Developer name of the case record type",
        "subject": "Short summary or title of the case",
        "complaint_status__c": "Status of the complaint (if applicable)",
        "response_status__c": "Status of the response sent to the customer",
        "redress_paid__c": "Indicates if redress compensation was paid (Yes/No)",
        "redress_amount__c": "Amount of redress compensation paid",
        "complaint_root_cause__c": "Root cause analysis of the complaint",
        "account": "Account details associated with the case",
        "account_attributes_type": "Type of the account associated with the case",
        "account_attributes_url": "URL link to the account details",
        "account_name": "Name of the account linked to the case",
        "isclosed": "Boolean value indicating if the case is closed (True/False)",
        "owner_attributes_type": "Type of the case owner (e.g., User, Queue)",
        "owner_attributes_url": "URL link to the owner’s details",
        "owner_name": "Name of the case owner (assigned agent)",
        "customer_status__c": "Current status of the customer (e.g., Active, Inactive)",
        "closure_requested_reason__c": "Reason provided for requesting case closure",
        "closure_requested_by__c": "Person who requested the case closure",
        "createdbyid": "Unique identifier of the user who created the case",
        "acknowledgement_sent__c": "Indicates if an acknowledgment was sent to the customer (Yes/No)",
        "sub_category__c": "Subcategory of the case issue",
        "date": "Date when the case record was processed",
        "timestamp_extracted": "Timestamp when the case data was extracted",
    },
    "salesforce_casehistory": {
        "id": "Unique identifier for each case history record",
        "isdeleted": "Flag indicating if the case history record has been deleted (true/false)",
        "caseid": "Unique identifier of the case related to this history record",
        "createdbyid": "Identifier of the user who created the case history record",
        "createddate": "Date and time when the case history record was created in Salesforce",
        "field": "Name of the field that was changed in the case",
        "newvalue": "New value of the field after the change",
        "case_attributes_type": "Salesforce object type for the case attributes",
        "case_attributes_url": "URL for the case attributes record",
        "case_casenumber": "Case number associated with the case history record",
        "case_account_attributes_type": "Salesforce object type for the case's account attributes",
        "case_account_attributes_url": "URL for the case's account attributes record",
        "case_account_id": "Identifier of the account associated with the case",
        "case_lastmodifieddate": "Date and time when the case was last modified",
        "case_closeddate": "Date and time when the case was closed",
        "case_account": "Additional account information associated with the case",
        "date": "Date when the case history entry was recorded",
        "timestamp_extracted": "Timestamp when the case history data was extracted for processing",
    },
    "salesforce_casemilestone": {
        "id": "The Salesforce case milestone ID",
        "caseid": "The Salesforce case ID",
        "startdate": "The Salesforce case start date",
        "targetdate": "The Salesforce case target date",
        "completiondate": "The Salesforce case completion date",
        "milestonetypeid": "The Salesforce milestone type id",
        "createddate": "The Salesforce case creation date",
        "lastmodifieddate": "The Salesforce case last modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_contact": {
        "id": "The Salesforce contact ID",
        "name": "Survey contact",
        "customer_cohort__c": "Identifies the group or segment of customers to which the individual belongs, based on characteristics, behaviors, or acquisition time.",
        "prior_customer_cohort__c": "Indicates the customer's previous cohort before any recent updates or changes.",
        "latest_cohort_change__c": "Date of the most recent change in the customer's cohort assignment.",
        "customer_intent__c": "Captures the customer's current intention or interest level in a product or service.",
        "intent_reason__c": "Describes the reason behind the customer's stated intent or lack thereof.",
        "last_call_date__c": "The date of the last call made to or received from the customer.",
        "ocp_call_1__c": "First outreach call placed to the customer.",
        "ocp_call_1_result__c": "Outcome of the first outreach call (e.g., interested, not interested, call back later).",
        "ocp_call_1_date__c": "Date of the first outreach call.",
        "ocp_call_2__c": "Second outreach call placed to the customer.",
        "ocp_call_2_result__c": "Outcome of the second outreach call.",
        "ocp_call_2_date__c": "Date of the second outreach call.",
        "ocp_call_3__c": "Third outreach call placed to the customer.",
        "ocp_call_3_result__c": "Outcome of the third outreach call.",
        "ocp_call_3_date__c": "Date of the third outreach call.",
        "final_call__c": "Indicates the last call made in a series of outreach attempts.",
        "final_call_attempt_date__c": "Date of the last attempted outreach call.",
        "final_call_projected_date__c": "Projected or planned date for the final call attempt.",
        "final_call_result__c": "Result of the final call attempt (e.g., successful contact, no answer, declined).",
        "pending_final_call__c": "call pending status",
        "fscs_eligible__c": "FSCS Eligible status",
        "care_of_address__c": "Care of Address",
        "beneficiary__c": "Beneficiary",
        "sanctioned__c": "Sanctioned status",
        "gone_away__c": "Gone Away status",
        "fraud_risk__c": "Fraud Risk status",
        "money_laundering_risk__c": "Money Laundering Risk status",
        "legal_status_code_deceased__c": "Legal Status Code Deceased",
        "special_modifications__c": "Special Modifications",
        "place_of_birth__c": "Place of birth of the contact",
        "tax_jurisdiction_1__c": "First tax jurisdiction of the contact",
        "jurisdiction_1_id_number__c": "ID number for the first tax jurisdiction",
        "tax_jurisdiction_2__c": "Second tax jurisdiction of the contact",
        "jurisdiction_2_id_number__c": "ID number for the second tax jurisdiction",
        "tax_jurisdiction_3__c": "Third tax jurisdiction of the contact",
        "jurisdiction_3_id_number__c": "ID number for the third tax jurisdiction",
        "isusperson__c": "Indicates if the contact is a US person",
        "createddate": "created date",
        "lastmodifieddate": "The Salesforce contact modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_emailmessage": {
        "id": "Unique identifier for each email message",
        "parentid": "Identifier for the parent record (e.g., related case or account)",
        "subject": "Subject line of the email message",
        "fromaddress": "Email address of the sender",
        "toaddress": "Email address(es) of the primary recipient(s)",
        "ccaddress": "Email address(es) of the CC'd recipient(s)",
        "createddate": "Date and time when the email message was created in Salesforce",
        "status": "Current processing status of the email message within the application",
        "textbody": "Plain text content of the email message",
        "htmlbody": "HTML formatted content of the email message",
        "date": "Date when the email message was originally sent",
        "timestamp_extracted": "Timestamp when the email message data was extracted for processing",
    },
    "salesforce_feedcomment": {
        "id": "Unique identifier for each feed comment",
        "feeditemid": "Identifier of the feed item to which this comment belongs",
        "parentid": "Identifier of the parent comment (if this is a reply to another comment)",
        "createdbyid": "Identifier of the user who created the comment",
        "createddate": "Date and time when the comment was created in Salesforce",
        "systemmodstamp": "System timestamp indicating the last modification date of the comment",
        "revision": "Revision number of the comment",
        "lasteditbyid": "Identifier of the user who last edited the comment",
        "lasteditdate": "Date and time when the comment was last edited",
        "commentbody": "Text content of the comment",
        "isdeleted": "Flag indicating if the comment has been deleted (true/false)",
        "insertedbyid": "Identifier of the user who inserted the comment, if different from the creator",
        "commenttype": "Type of the comment (e.g., 'Text', 'File')",
        "relatedrecordid": "Identifier of the related record, if any",
        "isrichtext": "Flag indicating if the comment body contains rich text (true/false)",
        "isverified": "Flag indicating if the comment has been verified (true/false)",
        "hasentitylinks": "Flag indicating if the comment contains links to other entities (true/false)",
        "status": "Current status of the comment within the application",
        "threadparentid": "Identifier of the parent thread, if this comment is part of a threaded discussion",
        "threadlevel": "Level of the comment within the thread (e.g., 1 for top-level comments)",
        "threadchildrencount": "Number of child comments under this comment in the thread",
        "threadlastupdated_date": "Date and time when the thread was last updated",
        "date": "Date when the comment was recorded",
        "timestamp_extracted": "Timestamp when the feed comment data was extracted for processing",
    },
    "salesforce_jointmortgages": {
        "id": "Unique identifier for each joint mortgage record",
        "casenumber": "Case number associated with the joint mortgage",
        "createddate": "The creation date of joint mortgages",
        "lastmodifieddate": "The last modified date of joint mortgages",
        "applicants__r": "Collection of applicant records related to the joint mortgage",
        "applicants__r_totalsize": "Total number of applicant records returned in the collection",
        "applicants__r_done": "Flag indicating if the retrieval of applicant records is complete (true/false)",
        "applicants__r_records_0_attributes_type": "Type attribute of the first applicant record",
        "applicants__r_records_0_attributes_url": "URL attribute of the first applicant record",
        "applicants__r_records_0_id": "Unique identifier of the first applicant record",
        "applicants__r_records_0_customer__c": "Customer ID of the first applicant",
        "applicants__r_records_0_customer__r_attributes_type": "Type attribute of the customer related to the first applicant",
        "applicants__r_records_0_customer__r_attributes_url": "URL attribute of the customer related to the first applicant",
        "applicants__r_records_0_customer__r_reference_id__c": "Reference ID of the customer related to the first applicant",
        "applicants__r_records_0_customer__r": "Details of the customer related to the first applicant",
        "applicants__r_records_1_attributes_type": "Type attribute of the second applicant record",
        "applicants__r_records_1_attributes_url": "URL attribute of the second applicant record",
        "applicants__r_records_1_id": "Unique identifier of the second applicant record",
        "applicants__r_records_1_customer__c": "Customer ID of the second applicant",
        "applicants__r_records_1_customer__r_attributes_type": "Type attribute of the customer related to the second applicant",
        "applicants__r_records_1_customer__r_attributes_url": "URL attribute of the customer related to the second applicant",
        "applicants__r_records_1_customer__r_reference_id__c": "Reference ID of the customer related to the second applicant",
        "applicants__r_records_1_customer__r": "Details of the customer related to the second applicant",
        "date": "Date when the joint mortgage record was created or last modified",
        "timestamp_extracted": "Timestamp when the joint mortgage data was extracted for processing",
    },
    "salesforce_milestonetype": {
        "id": "The Salesforce milestonetype ID",
        "name": "milestonetype name",
        "createddate": "The Salesforce milestonetype creation date",
        "lastmodifieddate": "The Salesforce milestonetype modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_propfin": {
        "id": "Unique identifier for each case",
        "casenumber": "Case number assigned to the application",
        "recordtypeid": "",
        "finance_amount__c": "The amount of finance requested",
        "fixed_rate_period__c": "The period for which the rate is fixed",
        "fixed_profit_rate__c": "The fixed profit rate for the finance",
        "opening_time__c": "Timestamp when the case was opened",
        "document_validation_completed_date__c": "Date when document validation was completed",
        "status": "Current status of the application",
        "valuation_stage__c": "The stage of valuation",
        "valuation_stage_completed_date__c": "Date when valuation stage was completed",
        "valuation_stage_started_date__c": "Date when valuation stage was started",
        "underwriting_stage_completed_date__c": "Date when underwriting stage was completed",
        "offer_generation_started_date__c": "Date when offer generation started",
        "offer_generation_completed_date__c": "Date when offer generation was completed",
        "fee_withdrawal_completed_date__c": "Date when fee withdrawal was completed",
        "final_payment_completed_date__c": "Date when final payment was completed",
        "case_completion_completed_date__c": "Date when the case completion was done",
        "property_finance_type__c": "Type of property finance",
        "broker_or_direct__c": "Whether the application came through a broker or was direct",
        "completion_date__c": "Date of completion of the finance case",
        "customer_reference_id__c": "Reference ID for the customer",
        "collateral_value__c": "Value of the collateral",
        "application_partner_name__c": "Name of the application partner",
        "city__c": "City of the property",
        "postal_code__c": "Postal code of the property",
        "contact_attributes_type": "Type of contact attributes",
        "contact_attributes_url": "URL for contact attributes",
        "contact_brand__c": "Brand associated with the contact",
        "contact_birthdate": "Birthdate of the contact",
        "delivery_country_code__c": "Country code for delivery",
        "owner_attributes_type": "Type of owner attributes",
        "owner_attributes_url": "URL for owner attributes",
        "owner_alias": "Alias of the owner",
        "repayment_period__c": "Repayment period for the finance",
        "application_fee__c": "Application fee charged",
        "legal_fee__c": "Legal fee associated with the application",
        "cost_of_funding__c": "Cost of funding",
        "description": "Description of the case",
        "murabaha_trade_started_date__c": "Started Date of Murabaha Trade",
        "murabaha_trade_completed_date__c": "Completed Date of Murabaha Trade",
        "transaction_type__c": "",
        "broker__c": "",
        "broker_firm__c": "",
        "valuation_type__c": "",
        "loan_type__c": "",
        "case_record_type_name__c": "",
        "createddate": "",
        "lastmodifieddate": "",
        "contact": "",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    },
    "salesforce_psd_form_c": {
        "administrator_frn__c": "Financial Registration Number (FRN) of the mortgage administrator",
        "first_borrower_dob__c": "Date of birth of the first borrower",
        "mortgage_acct_open_date__c": "Date when the mortgage account was opened",
        "original_mortgage_term_months__c": "Original term of the mortgage in months",
        "original_transaction_reference__c": "Reference number for the original mortgage transaction",
        "date_of_balance__c": "Date when the current balance was recorded",
        "original_size_of_loan__c": "Original size or amount of the loan",
        "original_provider_frn__c": "Financial Registration Number (FRN) of the original mortgage provider",
        "frn_of_beneficial_owner__c": "Financial Registration Number (FRN) of the beneficial owner",
        "name_of_legal_owner__c": "Name of the legal owner of the mortgage",
        "current_balance_outstanding__c": "Current outstanding balance on the mortgage",
        "current_expected_monthly_payment__c": "Current expected monthly payment amount",
        "current_gross_rate_of_interest__c": "Current gross rate of interest on the mortgage",
        "current_interest_rate_type__c": "Type of current interest rate (e.g., fixed, variable)",
        "current_rate_incentivised__c": "Flag indicating if the current rate is incentivized (true/false)",
        "date_incentivised_rate_ends__c": "Date when the incentivized interest rate ends",
        "remaining_term_months__c": "Remaining term of the mortgage in months",
        "months_past_maturity__c": "Number of months past the mortgage maturity date",
        "current_payment_shortfall__c": "Current shortfall in payment amount",
        "arrears_start_date__c": "Date when the mortgage account went into arrears",
        "formal_arrangement_for_shortfall__c": "Flag indicating if there is a formal arrangement for the payment shortfall (true/false)",
        "date_of_formal_arrangement__c": "Date when the formal arrangement for the payment shortfall was made",
        "capitalisation_of_payment_shortfall__c": "Flag indicating if the payment shortfall has been capitalized (true/false)",
        "capitalisation_date__c": "Date when the payment shortfall was capitalized",
        "date_of_interest_only_switch__c": "Date when the mortgage was switched to interest-only payments",
        "payments_suspended__c": "Flag indicating if payments are currently suspended (true/false)",
        "date_payments_suspended__c": "Date when payments were suspended",
        "date_of_reduced_payment__c": "Date when reduced payment terms began",
        "term_extension__c": "Flag indicating if the mortgage term has been extended (true/false)",
        "date_of_term_extension__c": "Date when the mortgage term was extended",
        "date_of_other_forbearance__c": "Date when other forbearance measures were applied",
        "date_litigation_action_started__c": "Date when litigation action was initiated",
        "date_of_possession__c": "Date when possession of the property was taken",
        "sale_value_achieved_for_repossessions__c": "Sale value achieved for the repossessed property",
        "case__c": "Reference to the case related to this mortgage record",
        "loan_purchased__c": "Flag indicating if the loan has been purchased (true/false)",
        "is_the_beneficial_owner_a_regulated_firm__c": "Flag indicating if the beneficial owner is a regulated firm (true/false)",
        "is_the_legal_owner_a_regulated_firm__c": "Flag indicating if the legal owner is a regulated firm (true/false)",
        "repayment_type__c": "Type of repayment plan (e.g., interest-only, principal and interest)",
        "reason_for_closure__c": "Reason for the closure of the mortgage account",
        "temporary_switch_to_interest_only__c": "Flag indicating if there was a temporary switch to interest-only payments (true/false)",
        "reduced_payment__c": "Flag indicating if the mortgage is on reduced payments (true/false)",
        "other_forbearance__c": "Flag indicating if other forbearance measures are in place (true/false)",
        "possession_order__c": "Flag indicating if a possession order has been issued (true/false)",
        "second_charge_mortgage__c": "Flag indicating if this is a second charge mortgage (true/false)",
        "is_the_account_part_of_a_closed_book__c": "Flag indicating if the mortgage account is part of a closed book (true/false)",
        "property_postcode__c": "Postcode of the property associated with the mortgage",
        "contact_reference_id__c": "Reference ID for the contact associated with the mortgage",
        "name_of_beneficial_owner__c": "Name of the beneficial owner of the mortgage",
        "frn_of_legal_owner__c": "Financial Registration Number (FRN) of the legal owner",
        "value_of_linked_accounts__c": "Value of accounts linked to the mortgage",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    },
    "salesforce_psd001_form_c": {
        "case__c": "Reference to the case related to this form",
        "type_of_valuation_at_origination__c": "Type of property valuation at the time of origination",
        "main_borrower_ccj__c": "County Court Judgments (CCJ) status of the main borrower",
        "second_borrower_ccj__c": "County Court Judgments (CCJ) status of the second borrower",
        "number_of_dependent_children__c": "Number of dependent children for the borrowers",
        "number_of_dependent_adults__c": "Number of dependent adults for the borrowers",
        "main_borrower_credit_history__c": "Credit history status of the main borrower",
        "second_borrower_credit_history__c": "Credit history status of the second borrower",
        "new_dwelling__c": "Flag indicating if the property is a new dwelling (true/false)",
        "mcob_11_7_used__c": "Flag indicating if MCOB 11.7 rule was used (true/false)",
        "first_borrower_basic_pay__c": "Basic pay of the first borrower",
        "first_borrower_other_employment__c": "Other employment income of the first borrower",
        "first_borrower_self_employment__c": "Self-employment income of the first borrower",
        "first_borrower_other_income__c": "Other income of the first borrower",
        "first_borrower_total_net_income__c": "Total net income of the first borrower",
        "x2nd_borrower_basic_pay__c": "Basic pay of the second borrower",
        "x2nd_borrower_other_employment__c": "Other employment income of the second borrower",
        "x2nd_borrower_self_employment__c": "Self-employment income of the second borrower",
        "x2nd_borrower_other_income__c": "Other income of the second borrower",
        "x2nd_borrower_total_net_income__c": "Total net income of the second borrower",
        "income_verification__c": "Verification status of the income (e.g., verified, unverified)",
        "total_credit_commitments__c": "Total credit commitments of the borrowers",
        "total_monthly_committed_expenditure__c": "Total monthly committed expenditure of the borrowers",
        "basic_household_expenditure__c": "Basic household expenditure of the borrowers",
        "stress_rate__c": "Stress rate applied to the mortgage",
        "advised_sale__c": " ",
        "borrower_dob__c": " ",
        "borrower_type__c": " ",
        "currency__c": " ",
        "date_of_mortgage_transaction__c": " ",
        "early_repayment_charge__c": " ",
        "fees_charges_added__c": " ",
        "firm_reference_number__c": " ",
        "first_borrower_employment_status__c": " ",
        "first_borrower_retirement_age__c": " ",
        "how_the_sale_was_made__c": " ",
        "initial_interest_rate__c": " ",
        "interest_rate_type__c": " ",
        "interest_roll_up_mortgage__c": " ",
        "intermediary_or_3rd_party_fees__c": " ",
        "lender_fees__c": " ",
        "mortgage_characteristics__c": " ",
        "number_of_borrowers_assessed__c": " ",
        "procuration_fee_paid__c": " ",
        "property_postcode__c": " ",
        "repayment_type__c": " ",
        "size_of_loan__c": " ",
        "transaction_reference_number__c": " ",
        "type_of_dwelling__c": " ",
        "type_of_mortgage__c": " ",
        "type_of_reversion_rate__c": " ",
        "x1st_borrower_basic_pay__c": " ",
        "x1st_borrower_other_employment__c": " ",
        "x1st_borrower_other_income__c": " ",
        "x1st_borrower_self_employment__c": " ",
        "x1st_borrower_total_net_income__c": " ",
        "amount_of_debt_consolidated__c": " ",
        "contractual_reversion_rate__c": " ",
        "customer_s_share_of_property__c": " ",
        "date_incentivised_rate_ends__c": " ",
        "date_of_original_mortgage_transaction__c": " ",
        "debt_secured_property_with_3rd_parties__c": " ",
        "debt_secured_property_with_same_lender__c": " ",
        "erc_end_date__c": " ",
        "government_initiative__c": " ",
        "money_withdrawn_for_remortgages__c": " ",
        "mortgage_term__c": " ",
        "original_transaction_reference__c": " ",
        "other_borrowers_basic_pay__c": " ",
        "other_borrowers_other_employment__c": " ",
        "other_borrowers_other_income__c": " ",
        "other_borrowers_self_employment__c": " ",
        "other_borrowers_total_net_income__c": " ",
        "percentage_interest_only_basis__c": " ",
        "property_value__c": " ",
        "purchase_price__c": " ",
        "purpose_of_further_advance_second_charge__c": " ",
        "rate_to_which_stress_test_was_applied__c": " ",
        "repayment_strategy__c": " ",
        "second_borrower_dob__c": " ",
        "second_borrower_employment_status__c": " ",
        "second_borrower_retirement_age__c": " ",
        "stress_test_rate__c": " ",
        "date": "Date of the case entry",
        "createddate": "Date of creation of psd001_form",
        "lastmodifieddate": "Date of modification of psd001_form",
        "timestamp_extracted": "Timestamp when the data was extracted",
    },
    "salesforce_rework_reason": {
        "id": "The Salesforce case rework reason taker ID",
        "Case_Re_work_Reason__c": "Case Re work Reason c",
        "createddate": "The Salesforce case creation date",
        "lastmodifieddate": "The Salesforce case modified date",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    },
    "salesforce_survey": {
        "id": "The Salesforce surveyquestionresponse taker ID",
        "name": "No of Survey responces",
        "createddate": "The Salesforce case creation date",
        "lastmodifieddate": "The Salesforce case modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_surveyquestion": {
        "id": "The Salesforce surveyquestion ID",
        "name": "survey question",
        "createddate": "The Salesforce surveyquestion creation date",
        "lastmodifieddate": "The Salesforce case modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_surveyquestionresponse": {
        "id": "The Salesforce surveyquestionresponse taker ID",
        "name": "Survey Questions are created with a name",
        "question_type__c": "Survey Question type",
        "response__c": "Survey Response",
        "response_numeric__c": "No of Survey Response",
        "survey_question__c": "Survey Question",
        "survey_taker__c": "Survey Taker",
        "survey__c": "Survey Answers are created for each question answered in the survey",
        "createddate": "The Salesforce case creation date",
        "lastmodifieddate": "The Salesforce case modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        # "response_english_text": "Survey Response in English",
        "date": "Date of the case entry",
    },
    "salesforce_surveytaker": {
        "id": "The Salesforce surveyquestionresponse taker ID",
        "name": "No of Survey responces",
        "survey__c": "Survey Answers are created for each question answered in the survey",
        "createddate": "The Salesforce case creation date",
        "lastmodifieddate": "The Salesforce case modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_user": {
        "id": "The Salesforce user ID",
        "name": "No of Survey responces",
        "createddate": "The Salesforce user creation date",
        "lastmodifieddate": "The Salesforce case modified date",
        "timestamp_extracted": "Timestamp when the data was extracted",
        "date": "Date of the case entry",
    },
    "salesforce_casenumber_valuation": {
        "contentdocument_attributes_type": "string",
        "contentdocument_attributes_url": "string",
        "contentdocument_id": "string",
        "contentdocument_createddate": "timestamp",
        "contentdocument_contentmodifieddate": "timestamp",
        "contentdocument_title": "string",
        "contentdocument_fileextension": "string",
        "contentdocument_latestpublishedversionid": "string",
        "linkedentityid": "string",
        "linkedentity_attributes_type": "string",
        "linkedentity_attributes_url": "string",
        "linkedentity_casenumber": "string",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_spv": {
        "account_number__c": "",
        "address_line_1__c": "",
        "address_line_2__c": "",
        "bank_name__c": "",
        "city__c": "",
        "company_email_address__c": "",
        "company_number__c": "",
        "company_phone_number__c": "",
        "createdbyid": "",
        "createddate": "",
        "duplicate_of_spv__c": "",
        "financial_institution_investment_entity__c": "",
        "id": "",
        "isdeleted": "",
        "lastactivitydate": "",
        "lastmodifiedbyid": "",
        "lastmodifieddate": "",
        "name": "",
        "number_of_properties_within_the_spv__c": "",
        "ownerid": "",
        "postcode__c": "",
        "sic_code__c": "",
        "sortcode__c": "",
        "spv_tax_identification_number_tin__c": "",
        "status__c": "",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_shareholders": {
        "id": "",
        "name": "",
        "customer__c": "",
        "number_of_rental_properties_excluded_own__c": "",
        "percentage_stake_in_this_spv__c": "",
        "shareholder_name__c": "",
        "special_purpose_vehicle__c": "",
        "lastmodifieddate": "",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_applicants": {
        "address_line_1__c": "",
        "address_rag_status__c": "",
        "address_rag_status_value__c": "",
        "app_form_completness_review__c": "",
        "applicant_name__c": "",
        "application_comments__c": "",
        "application_completed_date__c": "",
        "application_esis_attached__c": "",
        "application_esis_matched__c": "",
        "application_kyc_check_conducted__c": "",
        "application_stage_status__c": "",
        "application_started_date__c": "",
        "brand__c": "",
        "case__c": "",
        "case_record_type__c": "",
        "city__c": "",
        "createdbyid": "",
        "createddate": "",
        "customer__c": "",
        "customer_company_name__c": "",
        "customer_contact_phone_number__c": "",
        "customer_contactor_full_name__c": "",
        "customer_dob__c": "",
        "customer_email_address__c": "",
        "customer_internalreference__c": "",
        "customer_reference_id__c": "",
        "document_emp_bank_statement_comment__c": "",
        "document_emp_credit_report__c": "",
        "document_emp_credit_report_comments__c": "",
        "document_emp_payslips_employer_comments__c": "",
        "document_emp_payslips_employer_reference__c": "",
        "document_emp_personal_bank_statement__c": "",
        "document_selfe_certified_income_all_sour__c": "",
        "document_selfe_certified_income_comments__c": "",
        "document_selfe_credit_report__c": "",
        "document_selfe_credit_report_comments__c": "",
        "document_selfe_personal_bank_statement__c": "",
        "document_selfe_personal_stat_comments__c": "",
        "document_validation_completed_date__c": "",
        "document_validation_stage__c": "",
        "document_validation_started_date__c": "",
        "employed_other_documents__c": "",
        "employment_rag_status__c": "",
        "employment_rag_status_values__c": "",
        "employment_status__c": "",
        "id": "",
        "introducer_company_name__c": "",
        "introducer_email__c": "",
        "introducer_name__c": "",
        "introducer_telephone_number__c": "",
        "introducers_name__c": "",
        "isdeleted": "",
        "kyc_comments__c": "",
        "kyc_completed_date__c": "",
        "kyc_started_date__c": "",
        "lastactivitydate": "",
        "lastmodifiedbyid": "",
        "lastmodifieddate": "",
        "lastreferenceddate": "",
        "lastvieweddate": "",
        "mailing_country__c": "",
        "name": "",
        "no_rental_properties_excluding_this_one__c": "",
        "ownerid": "",
        "percentage_stake_in_this_spv__c": "",
        "postal_code__c": "",
        "primary_applicant__c": "",
        "status__c": "",
        "systemmodstamp": "",
        "unique_applicant__c": "",
        "timestamp_extracted": "",
        "date": ""
    },
}

schemas = {
    "salesforce_account": {
        "id": "string",
        "name": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_accounthistory": {
        "field": "string",
        "oldvalue": "string",
        "newvalue": "string",
        "accountid": "string",
        "createddate": "timestamp",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_cases": {
        "id": "string",
        "type": "string",
        "status": "string",
        "customer_reference_id__c": "string",
        "priority": "string",
        "description": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "closeddate": "timestamp",
        "ownerid": "string",
        "origin": "string",
        "contactid": "string",
        "casenumber": "string",
        "case_record_type_name__c": "string",
        "case_rt_dev_name__c": "string",
        "subject": "string",
        "complaint_status__c": "string",
        "response_status__c": "string",
        "redress_paid__c": "string",
        "redress_amount__c": "string",
        "complaint_root_cause__c": "string",
        "account": "string",
        "account_attributes_type": "string",
        "account_attributes_url": "string",
        "account_name": "string",
        "isclosed": "boolean",
        "owner_attributes_type": "string",
        "owner_attributes_url": "string",
        "owner_name": "string",
        "customer_status__c": "string",
        "closure_requested_reason__c": "string",
        "closure_requested_by__c": "string",
        "createdbyid": "string",
        "acknowledgement_sent__c": "string",
        "sub_category__c": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_casehistory": {
        "id": "string",
        "isdeleted": "boolean",
        "caseid": "string",
        "createdbyid": "string",
        "createddate": "timestamp",
        "field": "string",
        "newvalue": "string",
        "case_attributes_type": "string",
        "case_attributes_url": "string",
        "case_casenumber": "string",
        "case_account_attributes_type": "string",
        "case_account_attributes_url": "string",
        "case_account_id": "string",
        "case_lastmodifieddate": "timestamp",
        "case_closeddate": "timestamp",
        "case_account": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_casemilestone": {
        "id": "string",
        "caseid": "string",
        "startdate": "timestamp",
        "targetdate": "timestamp",
        "completiondate": "timestamp",
        "milestonetypeid": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_contact": {
        "id": "string",
        "name": "string",
        "customer_cohort__c": "string",
        "prior_customer_cohort__c": "string",
        "latest_cohort_change__c": "string",
        "customer_intent__c": "string",
        "intent_reason__c": "string",
        "last_call_date__c": "string",
        "ocp_call_1__c": "boolean",
        "ocp_call_1_result__c": "string",
        "ocp_call_1_date__c": "string",
        "ocp_call_2__c": "boolean",
        "ocp_call_2_result__c": "string",
        "ocp_call_2_date__c": "string",
        "ocp_call_3__c": "boolean",
        "ocp_call_3_result__c": "string",
        "ocp_call_3_date__c": "string",
        "final_call__c": "boolean",
        "final_call_attempt_date__c": "string",
        "final_call_projected_date__c": "string",
        "final_call_result__c": "string",
        "pending_final_call__c": "boolean",
        "fscs_eligible__c": "string",
        "care_of_address__c": "string",
        "beneficiary__c": "string",
        "sanctioned__c": "string",
        "gone_away__c": "string",
        "fraud_risk__c": "string",
        "money_laundering_risk__c": "string",
        "legal_status_code_deceased__c": "string",
        "special_modifications__c": "string",
        "place_of_birth__c": "string",
        "tax_jurisdiction_1__c": "string",
        "jurisdiction_1_id_number__c": "string",
        "tax_jurisdiction_2__c": "string",
        "jurisdiction_2_id_number__c": "string",
        "tax_jurisdiction_3__c": "string",
        "jurisdiction_3_id_number__c": "string",
        "isusperson__c": "boolean",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "Nationality__c": "string",
        "Tax_ID_locations__c": "string",
        "country_locations_risk_scores__c": "string",
        "asset_locations_scores__c": "string",
        "tax_id_locations_scores__c": "string",
        "bank_account_locations_scores__c": "string",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_emailmessage": {
        "id": "string",
        "parentid": "string",
        "subject": "string",
        "fromaddress": "string",
        "toaddress": "string",
        "ccaddress": "string",
        "createddate": "string",
        "status": "string",
        "textbody": "string",
        "htmlbody": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_feedcomment": {
        "id": "string",
        "feeditemid": "string",
        "parentid": "string",
        "createdbyid": "string",
        "createddate": "timestamp",
        "systemmodstamp": "timestamp",
        "revision": "string",
        "lasteditbyid": "string",
        "lasteditdate": "timestamp",
        "commentbody": "string",
        "isdeleted": "boolean",
        "insertedbyid": "string",
        "commenttype": "string",
        "relatedrecordid": "string",
        "isrichtext": "boolean",
        "isverified": "boolean",
        "hasentity_links": "string",
        "status": "string",
        "threadparentid": "string",
        "threadlevel": "string",
        "threadchildrencount": "string",
        "threadlastupdateddate": "timestamp",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_jointmortgages": {
        "id": "string",
        "casenumber": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "applicants__r": "string",
        "applicants__r_totalsize": "string",
        "applicants__r_done": "string",
        "applicants__r_records_0_attributes_type": "string",
        "applicants__r_records_0_attributes_url": "string",
        "applicants__r_records_0_id": "string",
        "applicants__r_records_0_customer__c": "string",
        "applicants__r_records_0_customer__r_attributes_type": "string",
        "applicants__r_records_0_customer__r_attributes_url": "string",
        "applicants__r_records_0_customer__r_reference_id__c": "string",
        "applicants__r_records_0_customer__r": "string",
        "applicants__r_records_1_attributes_type": "string",
        "applicants__r_records_1_attributes_url": "string",
        "applicants__r_records_1_id": "string",
        "applicants__r_records_1_customer__c": "string",
        "applicants__r_records_1_customer__r_attributes_type": "string",
        "applicants__r_records_1_customer__r_attributes_url": "string",
        "applicants__r_records_1_customer__r_reference_id__c": "string",
        "applicants__r_records_1_customer__r": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_milestonetype": {
        "id": "string",
        "name": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_propfin": {
        "id": "string",
        "casenumber": "string",
        "recordtypeid": "string",
        "finance_amount__c": "float",
        "fixed_rate_period__c": "string",
        "fixed_profit_rate__c": "string",
        "opening_time__c": "string",
        "document_validation_completed_date__c": "string",
        "status": "string",
        "valuation_stage__c": "string",
        "valuation_stage_completed_date__c": "string",
        "valuation_stage_started_date__c": "string",
        "underwriting_stage_completed_date__c": "string",
        "offer_generation_started_date__c": "string",
        "offer_generation_completed_date__c": "string",
        "fee_withdrawal_completed_date__c": "string",
        "final_payment_completed_date__c": "string",
        "case_completion_completed_date__c": "string",
        "property_finance_type__c": "string",
        "broker_or_direct__c": "string",
        "completion_date__c": "string",
        "customer_reference_id__c": "string",
        "collateral_value__c": "float",
        "application_partner_name__c": "string",
        "city__c": "string",
        "postal_code__c": "string",
        "contact_attributes_type": "string",
        "contact_attributes_url": "string",
        "contact_brand__c": "string",
        "contact_birthdate": "string",
        "delivery_country_code__c": "string",
        "owner_attributes_type": "string",
        "owner_attributes_url": "string",
        "owner_alias": "string",
        "repayment_period__c": "string",
        "application_fee__c": "string",
        "legal_fee__c": "string",
        "cost_of_funding__c": "float",
        "description": "string",
        "murabaha_trade_started_date__c": "string",
        "murabaha_trade_completed_date__c": "string",
        "transaction_type__c": "string",
        "broker__c": "string",
        "broker_firm__c": "string",
        "valuation_type__c": "string",
        "loan_type__c": "string",
        "case_record_type_name__c": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "contact": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_psd_form_c": {
        "administrator_frn__c": "string",
        "first_borrower_dob__c": "string",
        "mortgage_acct_open_date__c": "string",
        "original_mortgage_term_months__c": "string",
        "original_transaction_reference__c": "string",
        "date_of_balance__c": "string",
        "original_size_of_loan__c": "string",
        "original_provider_frn__c": "string",
        "frn_of_beneficial_owner__c": "string",
        "name_of_legal_owner__c": "string",
        "current_balance_outstanding__c": "string",
        "current_expected_monthly_payment__c": "string",
        "current_gross_rate_of_interest__c": "string",
        "current_interest_rate_type__c": "string",
        "current_rate_incentivised__c": "string",
        "date_incentivised_rate_ends__c": "string",
        "remaining_term_months__c": "string",
        "months_past_maturity__c": "string",
        "current_payment_shortfall__c": "string",
        "arrears_start_date__c": "string",
        "formal_arrangement_for_shortfall__c": "string",
        "date_of_formal_arrangement__c": "string",
        "capitalisation_of_payment_shortfall__c": "string",
        "capitalisation_date__c": "string",
        "date_of_interest_only_switch__c": "string",
        "payments_suspended__c": "string",
        "date_payments_suspended__c": "string",
        "date_of_reduced_payment__c": "string",
        "term_extension__c": "string",
        "date_of_term_extension__c": "string",
        "date_of_other_forbearance__c": "string",
        "date_litigation_action_started__c": "string",
        "date_of_possession__c": "string",
        "sale_value_achieved_for_repossessions__c": "string",
        "case__c": "string",
        "loan_purchased__c": "string",
        "is_the_beneficial_owner_a_regulated_firm__c": "string",
        "is_the_legal_owner_a_regulated_firm__c": "string",
        "repayment_type__c": "string",
        "reason_for_closure__c": "string",
        "temporary_switch_to_interest_only__c": "string",
        "reduced_payment__c": "string",
        "other_forbearance__c": "string",
        "possession_order__c": "string",
        "second_charge_mortgage__c": "string",
        "is_the_account_part_of_a_closed_book__c": "string",
        "property_postcode__c": "string",
        "contact_reference_id__c": "string",
        "name_of_beneficial_owner__c": "string",
        "frn_of_legal_owner__c": "string",
        "value_of_linked_accounts__c": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_psd001_form_c": {
        "case__c": "string",
        "type_of_valuation_at_origination__c": "string",
        "main_borrower_ccj__c": "string",
        "second_borrower_ccj__c": "string",
        "number_of_dependent_children__c": "double",
        "number_of_dependent_adults__c": "double",
        "main_borrower_credit_history__c": "string",
        "second_borrower_credit_history__c": "string",
        "new_dwelling__c": "string",
        "mcob_11_7_used__c": "string",
        "first_borrower_basic_pay__c": "double",
        "first_borrower_other_employment__c": "double",
        "first_borrower_self_employment__c": "double",
        "first_borrower_other_income__c": "double",
        "first_borrower_total_net_income__c": "double",
        "x2nd_borrower_basic_pay__c": "double",
        "x2nd_borrower_other_employment__c": "double",
        "x2nd_borrower_self_employment__c": "double",
        "x2nd_borrower_other_income__c": "double",
        "x2nd_borrower_total_net_income__c": "double",
        "income_verification__c": "string",
        "total_credit_commitments__c": "double",
        "total_monthly_committed_expenditure__c": "double",
        "basic_household_expenditure__c": "double",
        "stress_rate__c": "string",
        "advised_sale__c": "string",
        "borrower_dob__c": "string",
        "borrower_type__c": "string",
        "currency__c": "string",
        "date_of_mortgage_transaction__c": "timestamp",
        "early_repayment_charge__c": "string",
        "fees_charges_added__c": "string",
        "firm_reference_number__c": "string",
        "first_borrower_employment_status__c": "string",
        "first_borrower_retirement_age__c": "string",
        "how_the_sale_was_made__c": "string",
        "initial_interest_rate__c": "string",
        "interest_rate_type__c": "string",
        "interest_roll_up_mortgage__c": "string",
        "intermediary_or_3rd_party_fees__c": "string",
        "lender_fees__c": "string",
        "mortgage_characteristics__c": "string",
        "number_of_borrowers_assessed__c": "string",
        "procuration_fee_paid__c": "string",
        "property_postcode__c": "string",
        "repayment_type__c": "string",
        "size_of_loan__c": "string",
        "transaction_reference_number__c": "string",
        "type_of_dwelling__c": "string",
        "type_of_mortgage__c": "string",
        "type_of_reversion_rate__c": "string",
        "x1st_borrower_basic_pay__c": "string",
        "x1st_borrower_other_employment__c": "string",
        "x1st_borrower_other_income__c": "string",
        "x1st_borrower_self_employment__c": "string",
        "x1st_borrower_total_net_income__c": "string",
        "amount_of_debt_consolidated__c": "string",
        "contractual_reversion_rate__c": "string",
        "customer_s_share_of_property__c": "string",
        "date_incentivised_rate_ends__c": "timestamp",
        "date_of_original_mortgage_transaction__c": "timestamp",
        "debt_secured_property_with_3rd_parties__c": "string",
        "debt_secured_property_with_same_lender__c": "string",
        "erc_end_date__c": "timestamp",
        "government_initiative__c": "string",
        "money_withdrawn_for_remortgages__c": "string",
        "mortgage_term__c": "string",
        "original_transaction_reference__c": "string",
        "other_borrowers_basic_pay__c": "string",
        "other_borrowers_other_employment__c": "string",
        "other_borrowers_other_income__c": "string",
        "other_borrowers_self_employment__c": "string",
        "other_borrowers_total_net_income__c": "string",
        "percentage_interest_only_basis__c": "string",
        "property_value__c": "string",
        "purchase_price__c": "string",
        "purpose_of_further_advance_second_charge__c": "string",
        "rate_to_which_stress_test_was_applied__c": "string",
        "repayment_strategy__c": "string",
        "second_borrower_dob__c": "string",
        "second_borrower_employment_status__c": "string",
        "second_borrower_retirement_age__c": "string",
        "stress_test_rate__c": "string",
        "date": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_rework_reason": {
        "id": "string",
        "Case_Re_work_Reason__c": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "date": "string",
        "timestamp_extracted": "timestamp",
    },
    "salesforce_survey": {
        "id": "string",
        "name": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_surveyquestion": {
        "id": "string",
        "name": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_surveyquestionresponse": {
        "id": "string",
        "name": "string",
        "question_type__c": "string",
        "response__c": "string",
        "response_numeric__c": "string",
        "survey_question__c": "string",
        "survey_taker__c": "string",
        "survey__c": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        # "response_english_text": "string",
        "date": "string",
    },
    "salesforce_surveytaker": {
        "id": "string",
        "name": "string",
        "survey__c": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_user": {
        "id": "string",
        "name": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_casenumber_valuation": {
        "contentdocument_attributes_type": "string",
        "contentdocument_attributes_url": "string",
        "contentdocument_id": "string",
        "contentdocument_createddate": "timestamp",
        "contentdocument_contentmodifieddate": "timestamp",
        "contentdocument_title": "string",
        "contentdocument_fileextension": "string",
        "contentdocument_latestpublishedversionid": "string",
        "linkedentityid": "string",
        "linkedentity_attributes_type": "string",
        "linkedentity_attributes_url": "string",
        "linkedentity_casenumber": "string",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_applicants": {
        "address_line_1__c": "string",
        "address_rag_status__c": "string",
        "address_rag_status_value__c": "string",
        "app_form_completness_review__c": "string",
        "applicant_name__c": "string",
        "application_comments__c": "string",
        "application_completed_date__c": "string",
        "application_esis_attached__c": "boolean",
        "application_esis_matched__c": "boolean",
        "application_kyc_check_conducted__c": "string",
        "application_stage_status__c": "string",
        "application_started_date__c": "string",
        "brand__c": "string",
        "case__c": "string",
        "case_record_type__c": "string",
        "city__c": "string",
        "createdbyid": "string",
        "createddate": "string",
        "customer__c": "string",
        "customer_company_name__c": "string",
        "customer_contact_phone_number__c": "string",
        "customer_contactor_full_name__c": "string",
        "customer_dob__c": "string",
        "customer_email_address__c": "string",
        "customer_internalreference__c": "string",
        "customer_reference_id__c": "string",
        "document_emp_bank_statement_comment__c": "string",
        "document_emp_credit_report__c": "string",
        "document_emp_credit_report_comments__c": "string",
        "document_emp_payslips_employer_comments__c": "string",
        "document_emp_payslips_employer_reference__c": "string",
        "document_emp_personal_bank_statement__c": "string",
        "document_selfe_certified_income_all_sour__c": "string",
        "document_selfe_certified_income_comments__c": "string",
        "document_selfe_credit_report__c": "string",
        "document_selfe_credit_report_comments__c": "string",
        "document_selfe_personal_bank_statement__c": "string",
        "document_selfe_personal_stat_comments__c": "string",
        "document_validation_completed_date__c": "string",
        "document_validation_stage__c": "string",
        "document_validation_started_date__c": "string",
        "employed_other_documents__c": "string",
        "employment_rag_status__c": "string",
        "employment_rag_status_values__c": "string",
        "employment_status__c": "string",
        "id": "string",
        "introducer_company_name__c": "string",
        "introducer_email__c": "string",
        "introducer_name__c": "string",
        "introducer_telephone_number__c": "string",
        "introducers_name__c": "string",
        "isdeleted": "boolean",
        "kyc_comments__c": "string",
        "kyc_completed_date__c": "string",
        "kyc_started_date__c": "string",
        "lastactivitydate": "string",
        "lastmodifiedbyid": "string",
        "lastmodifieddate": "timestamp",
        "lastreferenceddate": "string",
        "lastvieweddate": "string",
        "mailing_country__c": "string",
        "name": "string",
        "no_rental_properties_excluding_this_one__c": "double",
        "ownerid": "string",
        "percentage_stake_in_this_spv__c": "double",
        "postal_code__c": "string",
        "primary_applicant__c": "boolean",
        "status__c": "string",
        "systemmodstamp": "string",
        "unique_applicant__c": "string",
        "timestamp_extracted": "timestamp",
        "date": "string"
    },
    "salesforce_shareholders": {
        "id": "string",
        "name": "string",
        "customer__c": "string",
        "number_of_rental_properties_excluded_own__c": "string",
        "percentage_stake_in_this_spv__c": "string",
        "shareholder_name__c": "string",
        "special_purpose_vehicle__c": "string",
        "lastmodifieddate": "timestamp",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "salesforce_spv": {
        "account_number__c": "string",
        "address_line_1__c": "string",
        "address_line_2__c": "string",
        "bank_name__c": "string",
        "city__c": "string",
        "company_email_address__c": "string",
        "company_number__c": "string",
        "company_phone_number__c": "string",
        "createdbyid": "string",
        "createddate": "string",
        "duplicate_of_spv__c": "string",
        "financial_institution_investment_entity__c": "string",
        "id": "string",
        "isdeleted": "boolean",
        "lastactivitydate": "timestamp",
        "lastmodifiedbyid": "string",
        "lastmodifieddate": "timestamp",
        "name": "string",
        "number_of_properties_within_the_spv__c": "string",
        "ownerid": "string",
        "postcode__c": "string",
        "sic_code__c": "string",
        "sortcode__c": "string",
        "spv_tax_identification_number_tin__c": "string",
        "status__c": "string",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
}
