with contact as (
    SELECT id,
        customer_cohort__c,
        prior_customer_cohort__c,
        latest_cohort_change__c,
        customer_intent__c,
        intent_reason__c,
        last_call_date__c,
        ocp_call_1__c,
        ocp_call_1_result__c,
        ocp_call_1_date__c,
        ocp_call_2__c,
        ocp_call_2_result__c,
        ocp_call_2_date__c,
        ocp_call_3__c,
        ocp_call_3_result__c,
        ocp_call_3_date__c,
        final_call__c,
        final_call_attempt_date__c,
        final_call_projected_date__c,
        final_call_result__c,
        pending_final_call__c
    FROM datalake_raw.salesforce_contact
    WHERE from_iso8601_timestamp(REPLACE(createddate, ' ', 'T')) > CAST('2023-06-16 00:00:00.000' AS TIMESTAMP)
)
select id,
    customer_cohort__c,
    prior_customer_cohort__c,
    latest_cohort_change__c,
    customer_intent__c,
    intent_reason__c,
    last_call_date__c,
    ocp_call_1__c,
    ocp_call_1_result__c,
    ocp_call_1_date__c,
    ocp_call_2__c,
    ocp_call_2_result__c,
    ocp_call_2_date__c,
    ocp_call_3__c,
    ocp_call_3_result__c,
    ocp_call_3_date__c,
    final_call__c,
    final_call_attempt_date__c,
    final_call_projected_date__c,
    final_call_result__c,
    pending_final_call__c
from contact
