column_comments = {
    "salesforce_psd_form_c": {
        "administrator_frn__c": "Financial Registration Number (FRN) of the mortgage administrator",
        "first_borrower_dob__c": "Date of birth of the first borrower",
        "mortgage_acct_open_date__c": "Date when the mortgage account was opened",
        "original_mortgage_term_months__c": "Original term of the mortgage in months",
        "original_transaction_reference__c": "Reference number for the original mortgage transaction",
        "date_of_balance__c": "Date when the current balance was recorded",
        "original_size_of_loan__c": "Original size or amount of the loan",
        "original_provider_frn__c": "Financial Registration Number (FRN) of the original mortgage provider",
        "frn_of_beneficial_owner__c": "Financial Registration Number (FRN) of the beneficial owner",
        "name_of_legal_owner__c": "Name of the legal owner of the mortgage",
        "current_balance_outstanding__c": "Current outstanding balance on the mortgage",
        "current_expected_monthly_payment__c": "Current expected monthly payment amount",
        "current_gross_rate_of_interest__c": "Current gross rate of interest on the mortgage",
        "current_interest_rate_type__c": "Type of current interest rate (e.g., fixed, variable)",
        "current_rate_incentivised__c": "Flag indicating if the current rate is incentivized (true/false)",
        "date_incentivised_rate_ends__c": "Date when the incentivized interest rate ends",
        "remaining_term_months__c": "Remaining term of the mortgage in months",
        "months_past_maturity__c": "Number of months past the mortgage maturity date",
        "current_payment_shortfall__c": "Current shortfall in payment amount",
        "arrears_start_date__c": "Date when the mortgage account went into arrears",
        "formal_arrangement_for_shortfall__c": "Flag indicating if there is a formal arrangement for the payment shortfall (true/false)",
        "date_of_formal_arrangement__c": "Date when the formal arrangement for the payment shortfall was made",
        "capitalisation_of_payment_shortfall__c": "Flag indicating if the payment shortfall has been capitalized (true/false)",
        "capitalisation_date__c": "Date when the payment shortfall was capitalized",
        "date_of_interest_only_switch__c": "Date when the mortgage was switched to interest-only payments",
        "payments_suspended__c": "Flag indicating if payments are currently suspended (true/false)",
        "date_payments_suspended__c": "Date when payments were suspended",
        "date_of_reduced_payment__c": "Date when reduced payment terms began",
        "term_extension__c": "Flag indicating if the mortgage term has been extended (true/false)",
        "date_of_term_extension__c": "Date when the mortgage term was extended",
        "date_of_other_forbearance__c": "Date when other forbearance measures were applied",
        "date_litigation_action_started__c": "Date when litigation action was initiated",
        "date_of_possession__c": "Date when possession of the property was taken",
        "sale_value_achieved_for_repossessions__c": "Sale value achieved for the repossessed property",
        "case__c": "Reference to the case related to this mortgage record",
        "loan_purchased__c": "Flag indicating if the loan has been purchased (true/false)",
        "is_the_beneficial_owner_a_regulated_firm__c": "Flag indicating if the beneficial owner is a regulated firm (true/false)",
        "is_the_legal_owner_a_regulated_firm__c": "Flag indicating if the legal owner is a regulated firm (true/false)",
        "repayment_type__c": "Type of repayment plan (e.g., interest-only, principal and interest)",
        "reason_for_closure__c": "Reason for the closure of the mortgage account",
        "temporary_switch_to_interest_only__c": "Flag indicating if there was a temporary switch to interest-only payments (true/false)",
        "reduced_payment__c": "Flag indicating if the mortgage is on reduced payments (true/false)",
        "other_forbearance__c": "Flag indicating if other forbearance measures are in place (true/false)",
        "possession_order__c": "Flag indicating if a possession order has been issued (true/false)",
        "second_charge_mortgage__c": "Flag indicating if this is a second charge mortgage (true/false)",
        "is_the_account_part_of_a_closed_book__c": "Flag indicating if the mortgage account is part of a closed book (true/false)",
        "property_postcode__c": "Postcode of the property associated with the mortgage",
        "contact_reference_id__c": "Reference ID for the contact associated with the mortgage",
        "name_of_beneficial_owner__c": "Name of the beneficial owner of the mortgage",
        "frn_of_legal_owner__c": "Financial Registration Number (FRN) of the legal owner",
        "value_of_linked_accounts__c": "Value of accounts linked to the mortgage",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    }
}


schemas = {
    "salesforce_psd_form_c": {
        "administrator_frn__c": "string",
        "first_borrower_dob__c": "string",
        "mortgage_acct_open_date__c": "string",
        "original_mortgage_term_months__c": "string",
        "original_transaction_reference__c": "string",
        "date_of_balance__c": "string",
        "original_size_of_loan__c": "string",
        "original_provider_frn__c": "string",
        "frn_of_beneficial_owner__c": "string",
        "name_of_legal_owner__c": "string",
        "current_balance_outstanding__c": "string",
        "current_expected_monthly_payment__c": "string",
        "current_gross_rate_of_interest__c": "string",
        "current_interest_rate_type__c": "string",
        "current_rate_incentivised__c": "string",
        "date_incentivised_rate_ends__c": "string",
        "remaining_term_months__c": "string",
        "months_past_maturity__c": "string",
        "current_payment_shortfall__c": "string",
        "arrears_start_date__c": "string",
        "formal_arrangement_for_shortfall__c": "string",
        "date_of_formal_arrangement__c": "string",
        "capitalisation_of_payment_shortfall__c": "string",
        "capitalisation_date__c": "string",
        "date_of_interest_only_switch__c": "string",
        "payments_suspended__c": "string",
        "date_payments_suspended__c": "string",
        "date_of_reduced_payment__c": "string",
        "term_extension__c": "string",
        "date_of_term_extension__c": "string",
        "date_of_other_forbearance__c": "string",
        "date_litigation_action_started__c": "string",
        "date_of_possession__c": "string",
        "sale_value_achieved_for_repossessions__c": "string",
        "case__c": "string",
        "loan_purchased__c": "string",
        "is_the_beneficial_owner_a_regulated_firm__c": "string",
        "is_the_legal_owner_a_regulated_firm__c": "string",
        "repayment_type__c": "string",
        "reason_for_closure__c": "string",
        "temporary_switch_to_interest_only__c": "string",
        "reduced_payment__c": "string",
        "other_forbearance__c": "string",
        "possession_order__c": "string",
        "second_charge_mortgage__c": "string",
        "is_the_account_part_of_a_closed_book__c": "string",
        "property_postcode__c": "string",
        "contact_reference_id__c": "string",
        "name_of_beneficial_owner__c": "string",
        "frn_of_legal_owner__c": "string",
        "value_of_linked_accounts__c": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    }
}
