column_comments = {
    "ga_278396662_data_view_1": {
        "dateHourMinute": "timestamp UTC0 of each record action date",
        "audienceName": "The given name of an Audience. Users are reported in the audiences to which they belonged during the report's date range. Current user behavior does not affect historical audience membership in reports.",
        "Country": "The country from which the user activity originated.",
        "language": "The language setting of the user's browser or device. For example, English.",
        "pagePath": "The portion of the URL between the hostname and query string for web pages visited.",
        "pageReferrer": "The full referring URL including the hostname and path. This referring URL is the user's previous URL and can be this website's domain or other domains.",
        "pageTitle": "The web page titles used on your site.",
        "fullPageUrl": "The hostname, page path, and query string for web pages visited.",
        "eventName": "The name of the event.",
        "eventCount": "The count of events.",
        "activeUsers": "The number of distinct users who visited your site or app.",
        "newUsers": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
        "totalUsers": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
        "sessions": "The number of sessions that began on your site or app (event triggered: session_start).",
        "date": "Partitioning column of date of each group of report's data.",
        "timestamp_extracted": "Timestamp UTC0 of when the data got processed.",
    },
    "ga_278396662_data_view_2": {
        "date": "Partitioning column of date of each group of report's data.",
        "country": "The country from which the user activity originated.",
        "activeUsers": "The number of distinct users who visited your site or app.",
        "newUsers": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
        "totalUsers": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
        "sessions": "The number of sessions that began on your site or app (event triggered: session_start).",
        "timestamp_extracted": "Timestamp UTC0 of when the data got processed.",
    },
    "ga_278396662_data_view_3": {
        "date": "Partitioning column of date of each group of report's data.",
        "country": "The country from which the user activity originated.",
        "firstusercustomchannelgroup:9877601687": "The custom channel that first acquired this user (Channel Group v2)",
        "totalusers": "The number of distinct users who have logged at least one event, regardless of whether the site or app was in use when that event was logged.",
        "activeusers": "The number of distinct users who visited your site or app.",
        "newusers": "The number of users who interacted with your site or launched your app for the first time (event triggered: first_open or first_visit).",
        "sessions": "The number of sessions that began on your site or app (event triggered: session_start).",
        "engagedsessions": "The number of sessions that lasted longer than 10 seconds, or had a key event, or had 2 or more screen views.",
        "engagementrate": "The percentage of engaged sessions (Engaged sessions divided by Sessions). This metric is returned as a fraction.",
        "userengagementduration": "The total amount of time (in seconds) your website or app was in the foreground of users` devices.",
        "eventcount": "The count of events.",
        "keyevents": "The count of key events. Marking an event as a key event affects reports from time of creation. It doesn't change historic data.",
        "userkeyeventrate": "The percentage of users who triggered any key event.",
        "timestamp_extracted": "Timestamp UTC0 of when the data got processed.",
    },
}


schemas = {
    "ga_278396662_data_view_1": {
        "dateHourMinute": "timestamp",
        "audienceName": "string",
        "Country": "string",
        "language": "string",
        "pagePath": "string",
        "pageReferrer": "string",
        "pageTitle": "string",
        "fullPageUrl": "string",
        "eventName": "string",
        "eventCount": "int",
        "activeUsers": "int",
        "newUsers": "int",
        "totalUsers": "int",
        "sessions": "int",
        "timestamp_extracted": "timestamp",
        "date": "string",
    },
    "ga_278396662_data_view_2": {
        "date": "string",
        "country": "string",
        "activeusers": "int",
        "newusers": "int",
        "totalusers": "int",
        "sessions": "int",
        "timestamp_extracted": "timestamp",
    },
    "ga_278396662_data_view_3": {
        "date": "string",
        "country": "string",
        "firstusercustomchannelgroup:9877601687": "string",
        "totalusers": "int",
        "activeusers": "int",
        "newusers": "int",
        "sessions": "int",
        "engagedsessions": "int",
        "engagementrate": "double",
        "userengagementduration": "int",
        "eventcount": "int",
        "keyevents": "int",
        "userkeyeventrate": "double",
        "timestamp_extracted": "timestamp",
    },
}
