column_comments = {
    "nice_skills_summary": {
        "business_unit_id": "The unique identifier for the business unit",
        "business_unit_name": "The name of the business unit",
        "abandon_count": "The number of calls that were abandoned by the caller before being handled",
        "abandon_rate": "The percentage of calls that were abandoned out of the total calls offered",
        "agents_acw": "The number of agents in After Call Work status",
        "agents_available": "The number of agents available to take a call",
        "agents_idle": "The number of agents idle and not handling calls",
        "agents_logged_in": "The total number of agents logged into the system",
        "agents_unavailable": "The number of agents logged in but unavailable to take calls",
        "agents_working": "The number of agents actively handling calls",
        "average_handle_time": "The average time spent handling a call, including talk and wrap-up time",
        "average_inqueue_time": "The average time a call spends in the queue before being answered",
        "average_speed_to_answer": "The average time it takes to answer a call once it is in the queue",
        "average_talk_time": "The average string of the actual conversation part of the call",
        "average_wrap_time": "The average time spent in after-call work, completing call-related tasks",
        "campaign_id": "The unique identifier for the campaign",
        "campaign_name": "The name of the campaign",
        "contacts_active": "The number of active contacts being handled at the moment",
        "contacts_handled": "The total number of contacts handled by agents",
        "contacts_offered": "The total number of contacts offered to agents",
        "contacts_queued": "The total number of contacts currently in queue",
        "contacts_out_of_sla": "The number of contacts that were not handled within the Service Level Agreement (SLA) time",
        "contacts_within_sla": "The number of contacts handled within the Service Level Agreement (SLA) time",
        "hold_time": "The total string of time calls spent on hold",
        "is_outbound": "Indicates if the call was outbound (true) or inbound (false)",
        "longest_queue_dur": "The string of the longest time a contact spent in the queue",
        "media_type_id": "The unique identifier for the type of media, e.g., phone call, chat, etc.",
        "media_type_name": "The name of the media type, e.g., Phone Call",
        "queue_count": "The number of contacts currently waiting in queue",
        "service_level": "The percentage of calls answered within the service level threshold time",
        "skill_name": "The name of the skill required to handle the contact",
        "skill_id": "The unique identifier for the skill",
        "service_level_goal": "The target service level percentage to be achieved",
        "service_level_threshold": "The maximum allowable time for a call to be answered to meet the service level goal",
        "total_contact_time": "The total time spent on contacts including talk, hold, and wrap time",
        "dials": "The number of outbound dials made",
        "connects": "The number of calls that were successfully connected",
        "connects_aht": "The average handle time for connected calls",
        "right_party_connects": "The number of outbound calls where the right party was reached",
        "right_party_connects_aht": "The average handle time for right party connects",
        "date": "Date of the case entry",
        "timestamp_extracted": "Timestamp when the data was extracted",
    }
}

schemas = {
    "nice_skills_summary": {
        "business_unit_id": "int",
        "business_unit_name": "string",
        "abandon_count": "int",
        "abandon_rate": "float",
        "agents_acw": "int",
        "agents_available": "int",
        "agents_idle": "int",
        "agents_logged_in": "int",
        "agents_unavailable": "int",
        "agents_working": "int",
        "average_handle_time": "string",
        "average_inqueue_time": "string",
        "average_speed_to_answer": "string",
        "average_talk_time": "string",
        "average_wrap_time": "string",
        "campaign_id": "int",
        "campaign_name": "string",
        "contacts_active": "int",
        "contacts_handled": "int",
        "contacts_offered": "int",
        "contacts_queued": "int",
        "contacts_out_of_sla": "int",
        "contacts_within_sla": "int",
        "hold_time": "string",
        "is_outbound": "boolean",
        "longest_queue_dur": "string",
        "media_type_id": "int",
        "media_type_name": "string",
        "queue_count": "int",
        "service_level": "float",
        "skill_name": "string",
        "skill_id": "int",
        "service_level_goal": "int",
        "service_level_threshold": "int",
        "total_contact_time": "string",
        "dials": "int",
        "connects": "int",
        "connects_aht": "string",
        "right_party_connects": "int",
        "right_party_connects_aht": "string",
        "date": "string",
        "timestamp_extracted": "timestamp",
    }
}
