column_comments = {
    "salesforce_psd001_form_c": {
        "case__c": "Reference to the case related to this form",
        "type_of_valuation_at_origination__c": "Type of property valuation at the time of origination",
        "main_borrower_ccj__c": "County Court Judgments (CCJ) status of the main borrower",
        "second_borrower_ccj__c": "County Court Judgments (CCJ) status of the second borrower",
        "number_of_dependent_children__c": "Number of dependent children for the borrowers",
        "number_of_dependent_adults__c": "Number of dependent adults for the borrowers",
        "main_borrower_credit_history__c": "Credit history status of the main borrower",
        "second_borrower_credit_history__c": "Credit history status of the second borrower",
        "new_dwelling__c": "Flag indicating if the property is a new dwelling (true/false)",
        "mcob_11_7_used__c": "Flag indicating if MCOB 11.7 rule was used (true/false)",
        "first_borrower_basic_pay__c": "Basic pay of the first borrower",
        "first_borrower_other_employment__c": "Other employment income of the first borrower",
        "first_borrower_self_employment__c": "Self-employment income of the first borrower",
        "first_borrower_other_income__c": "Other income of the first borrower",
        "first_borrower_total_net_income__c": "Total net income of the first borrower",
        "x2nd_borrower_basic_pay__c": "Basic pay of the second borrower",
        "x2nd_borrower_other_employment__c": "Other employment income of the second borrower",
        "x2nd_borrower_self_employment__c": "Self-employment income of the second borrower",
        "x2nd_borrower_other_income__c": "Other income of the second borrower",
        "x2nd_borrower_total_net_income__c": "Total net income of the second borrower",
        "income_verification__c": "Verification status of the income (e.g., verified, unverified)",
        "total_credit_commitments__c": "Total credit commitments of the borrowers",
        "total_monthly_committed_expenditure__c": "Total monthly committed expenditure of the borrowers",
        "basic_household_expenditure__c": "Basic household expenditure of the borrowers",
        "stress_rate__c": "Stress rate applied to the mortgage",
        "advised_sale__c": " ",
        "borrower_dob__c": " ",
        "borrower_type__c": " ",
        "currency__c": " ",
        "date_of_mortgage_transaction__c": " ",
        "early_repayment_charge__c": " ",
        "fees_charges_added__c": " ",
        "firm_reference_number__c": " ",
        "first_borrower_employment_status__c": " ",
        "first_borrower_retirement_age__c": " ",
        "how_the_sale_was_made__c": " ",
        "initial_interest_rate__c": " ",
        "interest_rate_type__c": " ",
        "interest_roll_up_mortgage__c": " ",
        "intermediary_or_3rd_party_fees__c": " ",
        "lender_fees__c": " ",
        "mortgage_characteristics__c": " ",
        "number_of_borrowers_assessed__c": " ",
        "procuration_fee_paid__c": " ",
        "property_postcode__c": " ",
        "repayment_type__c": " ",
        "size_of_loan__c": " ",
        "transaction_reference_number__c": " ",
        "type_of_dwelling__c": " ",
        "type_of_mortgage__c": " ",
        "type_of_reversion_rate__c": " ",
        "x1st_borrower_basic_pay__c": " ",
        "x1st_borrower_other_employment__c": " ",
        "x1st_borrower_other_income__c": " ",
        "x1st_borrower_self_employment__c": " ",
        "x1st_borrower_total_net_income__c": " ",
        "amount_of_debt_consolidated__c": " ",
        "contractual_reversion_rate__c": " ",
        "customer_s_share_of_property__c": " ",
        "date_incentivised_rate_ends__c": " ",
        "date_of_original_mortgage_transaction__c": " ",
        "debt_secured_property_with_3rd_parties__c": " ",
        "debt_secured_property_with_same_lender__c": " ",
        "erc_end_date__c": " ",
        "government_initiative__c": " ",
        "money_withdrawn_for_remortgages__c": " ",
        "mortgage_term__c": " ",
        "original_transaction_reference__c": " ",
        "other_borrowers_basic_pay__c": " ",
        "other_borrowers_other_employment__c": " ",
        "other_borrowers_other_income__c": " ",
        "other_borrowers_self_employment__c": " ",
        "other_borrowers_total_net_income__c": " ",
        "percentage_interest_only_basis__c": " ",
        "property_value__c": " ",
        "purchase_price__c": " ",
        "purpose_of_further_advance_second_charge__c": " ",
        "rate_to_which_stress_test_was_applied__c": " ",
        "repayment_strategy__c": " ",
        "second_borrower_dob__c": " ",
        "second_borrower_employment_status__c": " ",
        "second_borrower_retirement_age__c": " ",
        "stress_test_rate__c": " ",
        "date": "Date of the case entry",
        "createddate": "Date of creation of psd001_form",
        "lastmodifieddate": "Date of modification of psd001_form",
        "property_finance_type__c": " ",
        "status": " ",
        "Completion_Date__c": " ",
        "timestamp_extracted": "Timestamp when the data was extracted"
    }
}


schemas = {
    "salesforce_psd001_form_c": {
        "case__c": "string",
        "type_of_valuation_at_origination__c": "string",
        "main_borrower_ccj__c": "string",
        "second_borrower_ccj__c": "string",
        "number_of_dependent_children__c": "double",
        "number_of_dependent_adults__c": "double",
        "main_borrower_credit_history__c": "string",
        "second_borrower_credit_history__c": "string",
        "new_dwelling__c": "string",
        "mcob_11_7_used__c": "string",
        "first_borrower_basic_pay__c": "double",
        "first_borrower_other_employment__c": "double",
        "first_borrower_self_employment__c": "double",
        "first_borrower_other_income__c": "double",
        "first_borrower_total_net_income__c": "double",
        "x2nd_borrower_basic_pay__c": "double",
        "x2nd_borrower_other_employment__c": "double",
        "x2nd_borrower_self_employment__c": "double",
        "x2nd_borrower_other_income__c": "double",
        "x2nd_borrower_total_net_income__c": "double",
        "income_verification__c": "string",
        "total_credit_commitments__c": "double",
        "total_monthly_committed_expenditure__c": "double",
        "basic_household_expenditure__c": "double",
        "stress_rate__c": "string",
        "advised_sale__c": "string",
        "borrower_dob__c": "string",
        "borrower_type__c": "string",
        "currency__c": "string",
        "date_of_mortgage_transaction__c":"timestamp",
        "early_repayment_charge__c": "string",
        "fees_charges_added__c": "string",
        "firm_reference_number__c": "string",
        "first_borrower_employment_status__c": "string",
        "first_borrower_retirement_age__c": "string",
        "how_the_sale_was_made__c": "string",
        "initial_interest_rate__c": "string",
        "interest_rate_type__c": "string",
        "interest_roll_up_mortgage__c": "string",
        "intermediary_or_3rd_party_fees__c": "string",
        "lender_fees__c": "string",
        "mortgage_characteristics__c": "string",
        "number_of_borrowers_assessed__c": "string",
        "procuration_fee_paid__c": "string",
        "property_postcode__c": "string",
        "repayment_type__c": "string",
        "size_of_loan__c": "string",
        "transaction_reference_number__c": "string",
        "type_of_dwelling__c": "string",
        "type_of_mortgage__c": "string",
        "type_of_reversion_rate__c": "string",
        "x1st_borrower_basic_pay__c": "string",
        "x1st_borrower_other_employment__c": "string",
        "x1st_borrower_other_income__c": "string",
        "x1st_borrower_self_employment__c" : "string",
        "x1st_borrower_total_net_income__c": "string",
        "amount_of_debt_consolidated__c": "string",
        "contractual_reversion_rate__c": "string",
        "customer_s_share_of_property__c": "string",
        "date_incentivised_rate_ends__c": "timestamp",
        "date_of_original_mortgage_transaction__c": "timestamp",
        "debt_secured_property_with_3rd_parties__c": "string",
        "debt_secured_property_with_same_lender__c": "string",
        "erc_end_date__c": "timestamp",
        "government_initiative__c": "string",
        "money_withdrawn_for_remortgages__c": "string",
        "mortgage_term__c": "string",
        "original_transaction_reference__c": "string",
        "other_borrowers_basic_pay__c": "string",
        "other_borrowers_other_employment__c": "string",
        "other_borrowers_other_income__c": "string",
        "other_borrowers_self_employment__c": "string",
        "other_borrowers_total_net_income__c": "string",
        "percentage_interest_only_basis__c": "string",
        "property_value__c": "string",
        "purchase_price__c": "string",
        "purpose_of_further_advance_second_charge__c": "string",
        "rate_to_which_stress_test_was_applied__c": "string",
        "repayment_strategy__c": "string",
        "second_borrower_dob__c": "string",
        "second_borrower_employment_status__c": "string",
        "second_borrower_retirement_age__c": "string",
        "stress_test_rate__c": "string",
        "date": "string",
        "createddate": "timestamp",
        "lastmodifieddate": "timestamp",
        "property_finance_type__c": "string",
        "status": "string",
        "Completion_Date__c": "timestamp",
        "timestamp_extracted": "timestamp",
    }
}
