config = {
    "queries": {
        "salesforce_account": "q=SELECT Id, Name, CreatedDate, LastModifiedDate FROM Account",
        "salesforce_valuation": """q=SELECT ContentDocument.Id, ContentDocument.Title, ContentDocument.FileExtension, ContentDocument.CreatedDate,
            ContentDocument.LatestPublishedVersionId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN (SELECT Id FROM Case)""",
        "salesforce_casenumber_valuation": """q=SELECT ContentDocument.Id, ContentDocument.Title, ContentDocument.FileExtension, ContentDocument.CreatedDate
            ContentDocument.LatestPublishedVersionId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN (SELECT Id FROM Case)""",
        "salesforce_emailmessage": "q=SELECT Id, ParentId, Subject, FromAddress, ToAddress, CcAddress, CreatedDate, Status, TextBody, HtmlBody FROM EmailMessage where CreatedDate =YESTERDAY",
        "salesforce_emailmessage_backfill": "q=SELECT Id, ParentId, Subject, FromAddress, ToAddress, CcAddress, CreatedDate, Status, TextBody, HtmlBody FROM EmailMessage",
        "salesforce_accounthistory": "q=SELECT Field, OldValue, NewValue, AccountId, CreatedDate FROM AccountHistory",
        "salesforce_cases": """q=SELECT Id, Type, Status, Customer_Reference_Id__c, priority, description, CreatedDate, LastModifiedDate,
            ClosedDate, OwnerId, Origin, ContactId, CaseNumber, case_record_type_name__c, Case_RT_Dev_Name__c, Subject, complaint_status__c,
            response_status__c, redress_paid__c, redress_amount__c, Complaint_Root_Cause__c, Account.Name, IsClosed, Owner.Name, Customer_Status__c,
            Closure_Requested_Reason__c, Closure_requested_by__c, CreatedById, acknowledgement_sent__c, sub_category__c FROM Case""",
        "salesforce_jointmortgages": """q=select Id, CaseNumber, CreatedDate, LastModifiedDate, (SELECT Id, Customer__c, Customer__r.Reference_Id__c FROM Applicants__r)
        FROM Case WHERE RecordType.DeveloperName = 'Joint_Finance_Residential_Introducer_Application'""",
        "salesforce_casehistory": """q=select Id, IsDeleted, CaseId, CreatedById, CreatedDate, Field, NewValue, Case.CaseNumber, case.Account.Id,
        Case.LastModifiedDate, case.ClosedDate from CaseHistory""",
        "salesforce_casehistory_backfill": """q=select Id, IsDeleted, CaseId, CreatedById, CreatedDate, Field, NewValue, Case.CaseNumber, case.Account.Id,
        Case.LastModifiedDate, case.ClosedDate from CaseHistory""",
        "salesforce_feedcomment": """q=select Id, FeedItemId, ParentId, CreatedById, CreatedDate, SystemModstamp, Revision, LastEditById, LastEditDate,
        CommentBody, IsDeleted, InsertedById, CommentType, RelatedRecordId, IsRichText, IsVerified, HasEntityLinks, Status, ThreadParentId, ThreadLevel,
        ThreadChildrenCount, ThreadLastUpdatedDate from FeedComment""",
        "salesforce_feedcomment_backfill": """q=select Id, FeedItemId, ParentId, CreatedById, CreatedDate, SystemModstamp, Revision, LastEditById, LastEditDate,
        CommentBody, IsDeleted, InsertedById, CommentType, RelatedRecordId, IsRichText, IsVerified, HasEntityLinks, Status, ThreadParentId, ThreadLevel,
        ThreadChildrenCount, ThreadLastUpdatedDate from FeedComment""",
        "salesforce_casemilestone": "q=SELECT Id, CaseId, StartDate, TargetDate, CompletionDate, MilestoneTypeId, CreatedDate, LastModifiedDate FROM CaseMilestone",
        "salesforce_contact": """q=select Id, Name, Customer_Cohort__c, Prior_Customer_Cohort__c, Latest_Cohort_Change__c,
            Customer_Intent__c, Intent_Reason__c, Last_Call_Date__c, OCP_Call_1__c, OCP_Call_1_Result__c,
            OCP_Call_1_Date__c, OCP_Call_2__c, OCP_Call_2_Result__c, OCP_Call_2_Date__c, OCP_Call_3__c,
            OCP_Call_3_Result__c, OCP_Call_3_Date__c, Final_Call__c, Final_Call_Attempt_Date__c,
            Final_Call_Projected_Date__c, Final_Call_Result__c, Pending_Final_Call__c,
            FSCS_Eligible__c, Care_Of_Address__c, Beneficiary__c, Sanctioned__c, Gone_Away__c,
            Fraud_Risk__c, Money_Laundering_Risk__c, Legal_Status_Code_Deceased__c,
            Special_Modifications__c, place_of_birth__c, tax_jurisdiction_1__c, jurisdiction_1_id_number__c,
            tax_jurisdiction_2__c, jurisdiction_2_id_number__c, tax_jurisdiction_3__c,
            jurisdiction_3_id_number__c, isUsPerson__c, CreatedDate, LastModifiedDate,
            Nationality__c, Tax_ID_locations__c, country_locations_risk_scores__c,
            asset_locations_scores__c, tax_id_locations_scores__c,
            bank_account_locations_scores__c from Contact where LastModifiedDate >{start_date}""",
        "salesforce_propfin": """q=select id, CaseNumber, Finance_amount__c, Fixed_rate_period__c, Fixed_Profit_Rate__c, Opening_Time__c,
            Document_Validation_Completed_Date__c, Status, Valuation_Stage__c, Valuation_Stage_Completed_Date__c, Valuation_Stage_Started_Date__c,
            Underwriting_Stage_Completed_Date__c, Offer_Generation_Started_Date__c, Offer_Generation_Completed_Date__c,
            Fee_Withdrawal_Completed_Date__c, Final_Payment_Completed_Date__c, Case_Completion_Completed_Date__c,
            Property_Finance_Type__c, Broker_or_Direct__c, Completion_Date__c, Customer_Reference_Id__c, Collateral_Value__c,
            Application_Partner_name__c, City__c, Postal_code__c, Contact.Brand__c, delivery_country_code__c, Owner.Alias,
            Contact.Birthdate, Repayment_period__c, Application_Fee__c, Legal_Fee__c, Cost_of_Funding__c, Description, Murabaha_Trade_Started_Date__c,
            Murabaha_Trade_Completed_Date__c, Transaction_Type__c, Broker__c, Broker_Firm__c, Valuation_Type__c, Loan_Type__c, CreatedDate, LastModifiedDate from Case where Property_Finance_Type__c IN ('Rental','Residential') """,
        "salesforce_rework_reason": "q=select Id, Case_Re_work_Reason__c, CreatedDate, LastModifiedDate FROM Case",
        "salesforce_survey": "q=SELECT Id, Name, CreatedDate, LastModifiedDate FROM Survey__c",
        "salesforce_surveytaker": "q=SELECT Id, Name, Survey__c, CreatedDate, LastModifiedDate FROM SurveyTaker__c",
        "salesforce_surveyquestion": "q=SELECT Id, Name, CreatedDate, LastModifiedDate FROM Survey_Question__c",
        "salesforce_surveyquestionresponse": "q=SELECT Id, Name, Question_Type__c, Response__c, Response_Numeric__c, Survey_Question__c, SurveyTaker__c, Survey__c, CreatedDate, LastModifiedDate FROM SurveyQuestionResponse__c",
        "salesforce_user": "q=SELECT Id, Name, CreatedDate, LastModifiedDate FROM User",
        "salesforce_milestonetype": "q=SELECT Id, Name, CreatedDate, LastModifiedDate FROM MilestoneType",
        "salesforce_psd_form_c": """q=select Administrator_FRN__c,First_borrower_DOB__c,Mortgage_acct_open_date__c,Original_mortgage_term_months__c,
            Original_transaction_reference__c,Date_of_balance__c,Original_size_of_loan__c,Original_provider_FRN__c,FRN_of_beneficial_owner__c,
            Name_of_legal_owner__c,Current_balance_outstanding__c,Current_expected_monthly_payment__c,Current_gross_rate_of_interest__c,
            Current_interest_rate_type__c,Current_rate_incentivised__c,Date_incentivised_rate_ends__c,Remaining_term_months__c,Months_past_maturity__c,
            Current_payment_shortfall__c,Arrears_start_date__c,Formal_arrangement_for_shortfall__c,Date_of_formal_arrangement__c,Capitalisation_of_payment_shortfall__c,
            Capitalisation_date__c,Date_of_interest_only_switch__c,Payments_suspended__c,Date_payments_suspended__c,Date_of_reduced_payment__c,Term_extension__c,
            Date_of_term_extension__c,Date_of_other_forbearance__c,Date_litigation_action_started__c,Date_of_possession__c,Sale_value_achieved_for_repossessions__c,
            Case__c,Loan_purchased__c,Is_the_beneficial_owner_a_regulated_firm__c,Is_the_legal_owner_a_regulated_firm__c,Repayment_type__c,Reason_for_closure__c,
            Temporary_switch_to_interest_only__c,Reduced_payment__c,Other_forbearance__c,Possession_order__c,Second_charge_mortgage__c,Is_the_account_part_of_a_closed_book__c,
            Property_postcode__c,Contact_Reference_Id__c,Name_of_beneficial_owner__c,FRN_of_legal_owner__c,
            Value_of_linked_accounts__c, CreatedDate from PSD_Form__c""",
        "salesforce_psd001_form_c": """q=select Case__c,Type_of_valuation_at_origination__c,Main_borrower_CCJ__c,Second_borrower_CCJ__c,
            Number_of_dependent_children__c,Dependent_children__c,Number_of_dependent_adults__c,Dependent_adults__c,Main_borrower_Credit_History__c,Second_borrower_credit_history__c,
            New_Dwelling__c,MCOB_11_7_used__c,First_Borrower_Basic_Pay__c,First_Borrower_Other_Employment__c,First_Borrower_self_employment__c,
            First_borrower_Other_Income__c,First_Borrower_Total_Net_income__c,X2nd_borrower_basic_pay__c,X2nd_borrower_other_employment__c,
            X2nd_borrower_self_employment__c,X2nd_borrower_other_income__c,X2nd_borrower_total_net_income__c,Income_Verification__c,Total_Credit_Commitments__c,
            Total_Monthly_Committed_expenditure__c,Basic_Household_expenditure__c,Stress_Rate__c,Advised_sale__c,Borrower_DOB__c,Borrower_type__c,Currency__c, 
            Date_of_mortgage_transaction__c,Early_repayment_charge__c,Fees_charges_added__c,Firm_Reference_Number__c,First_borrower_employment_status__c, 
            First_borrower_retirement_age__c,How_the_sale_was_made__c,Initial_interest_rate__c,Interest_rate_type__c,Interest_roll_up_mortgage__c, 
            Intermediary_or_3rd_party_fees__c,Lender_fees__c,Mortgage_characteristics__c,Number_of_borrowers_assessed__c,Procuration_fee_paid__c,Property_postcode__c, 
            Repayment_type__c,Size_of_loan__c,Transaction_Reference_Number__c,Type_of_dwelling__c,Type_of_mortgage__c,Type_of_reversion_rate__c,X1st_borrower_basic_pay__c, 
            X1st_borrower_other_employment__c,X1st_borrower_other_income__c,X1st_borrower_self_employment__c,X1st_borrower_total_net_income__c,Amount_of_debt_consolidated__c, 
            Contractual_reversion_rate__c,Customer_s_share_of_property__c,Date_incentivised_rate_ends__c,Date_of_original_mortgage_transaction__c, 
            Debt_secured_property_with_3rd_parties__c,Debt_secured_property_with_same_lender__c,ERC_end_date__c,Government_initiative__c,Money_withdrawn_for_remortgages__c, 
            Mortgage_term__c,Original_transaction_reference__c,Other_borrowers_basic_pay__c,Other_borrowers_other_employment__c,Other_borrowers_other_income__c, 
            Other_borrowers_self_employment__c,Other_borrowers_total_net_income__c,Percentage_interest_only_basis__c,Property_value__c,Purchase_price__c, 
            Purpose_of_further_advance_second_charge__c,Rate_to_which_stress_test_was_applied__c,Repayment_strategy__c,Second_borrower_DOB__c, 
            Second_borrower_employment_status__c,Second_borrower_retirement_age__c,Stress_test_rate__c,CreatedDate,LastModifiedDate,Case__r.Property_Finance_Type__c,Case__r.status,Case__r.Completion_Date__c from PSD001_Form__c""",
    },
}
